config/routes.rb
Rails.application.routes.draw do
  get 'nices/create'
  get 'nices/destroy'
  root to: 'questions#index'
  devise_for :users
  resources :users, only: :show

  resources :questions do
    resources :answers
  end

  resources :questions do
    resources :likes, only: [:create, :destroy]
  end

  resources :answers do
    resources :nices, only: [:create, :destroy]
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  has_many :nices, dependent: :destroy
  validates :text, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bestanswer.rb
class Bestanswer < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/nice.rb
class Nice < ApplicationRecord
  belongs_to :user
  belongs_to :answer
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :likes, dependent: :destroy
  
  validates :title, :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :nices, dependent: :destroy

  def already_liked?(question)
    self.likes.exists?(question_id: question.id)
  end

  def already_niced?(answer)
    self.nices.exists?(answer_id: answer.id)
  end

  with_options presence: true do
  validates :password, format: { with: /\A[a-z0-9]+\z/ , message: ' 半角英数字で入力してください' }
  validates :name
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @answer = Answer.new(answer_params)
    if @answer.valid?
        @answer.save
        redirect_to "/questions/#{@answer.question.id}"
    else
        redirect_to "/questions/#{@answer.question.id}"
    end
  end

  private
  def answer_params
    params.require(:answer).permit(:text).merge(user_id: current_user.id, question_id: params[:question_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @likes = current_user.likes.create(question_id: params[:question_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(question_id: params[:question_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/nices_controller.rb
class NicesController < ApplicationController
  def create
    @nices = current_user.nices.create(answer_id: params[:answer_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @nice = nice.find_by(answer_id: params[:answer_id], user_id: current_user.id)
    @nice.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.includes(:user).order('created_at DESC')
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.valid?
      @question.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @answer = Answer.new
    @answers = @question.answers.includes(:user)
    @like = Like.new
    @nice = Nice.new
    @like = Like.find_by(question_id: params[:question_id], user_id: @like.id)
    @nice = Nice.find_by(answer_id: params[:answer_id], user_id: @nice.id)

  end

  def edit
    unless current_user.id == @question.user.id
      redirect_to root_path
    end
  end

  def update
    if @question.update(question_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if current_user.id == @question.user.id
      @question.destroy
      redirect_to root_path
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :text).merge(user_id: current_user.id)
  end

  def set_tweet
    @question = Question.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @name = user.name
    @questions = user.questions.order('created_at DESC')
    @answers = user.answers.order('created_at DESC')
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/nices_helper.rb
module NicesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render "shared/header" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
<%= yield %>
  </body>
  <footer>
      <p>
       <small>Copyright (c) FES All Rights Reserved.</small>
      </p>
    </footer>
</html>

app/views/questions/edit.html.erb
<%= render "shared/error_messages", model: @question %>

<%= form_with model: @question, url: question_path, local: true do |f| %>
<div class="content-row">
  <div class= "question-row">
    <div class= "title-question">
      <%= f.text_field :title, placeholder: "タイトル", size:10*10, class:"title-question" %>
    </div>
    <div class= "text-question">
      <%= f.text_area :text, placeholder: "内容", class:"text-question",rows: "10" %>
    </div>
      <%= f.submit "変更",class:"button" %>
  </div>
  <% end %>
</div>

app/views/questions/index.html.erb
  <div class ='question-main'>
    <div class='question-contents'>
      <h4 class='title'>質問コーナー</h4>
        <%= link_to 'NEW質問集', "", class: "subtitle" %>
        <% @questions.each do |question| %>
        <div class= "questions">
          <div class= "more">
            <span><%= image_tag 'arrow_top.png' %></span>
            <ul class="more-list">
              <li class= "list">
                <%= link_to '詳細', question_path(question.id), method: :get %>
              </li>
              <% if user_signed_in? && current_user.id == question.user_id %>
                <li class= "list">
                  <%= link_to '編集', edit_question_path(question.id), method: :get %>
                </li>
                <li class= "list">
                  <%= link_to '削除', question_path(question.id), method: :delete %>
                </li>
              <% end %>
            </ul>
          </div>
          <div class= "question-title">
              title:<%= question.title %>
          </div> 
          <div class= "question-text">
            Q:<%= link_to question.text, question_path(question.id) %>
          </div>
          <div class="question-date">
            <%= l question.created_at %>
            by<%= link_to question.user.name, user_path(question.user.id), class:'ac' %>
          </div>
        </div>
        <% end %>
    </div>
  </div>
  <div class ='question-main'>
    <div class='question-contents'>
    </div>
    </div>
</div>

app/views/questions/new.html.erb
<%= render "shared/error_messages", model: @question %>

<%= form_with model: @question, url: questions_path, local: true do |f| %>
<div class="content-row">
  <div class= "question-row">
    <div class= "title-question">
      <%= f.text_field :title, placeholder: "タイトル", size:10*10, class:"title-question"%>
    </div>
    <div class= "text-question">
      <%= f.text_area :text, placeholder: "内容", class:"text-question", rows: "10" %>
    </div>
      <%= f.submit "質問",class:"button" %>
  </div>
  <% end %>
</div>

app/views/questions/show.html.erb
<div class="show-box">
  <div class="box">
    <div class="q-name">
        <a href="/users/<%= @question.user.id %>">
          投稿者<%= @question.user.name %>
        </a>
    </div>
    <div class= "q-title">
      <div class= "title">title:<%= @question.title %></div>
    </div>
    <div class="user-text">
      <div class= "rr">Q:<%= @question.text %>
        <div class = "date"><%= l @question.created_at %>
          <div class="like-link" id="like-link-<%= @question.id %>">
            <% if user_signed_in? %>
              <% if current_user.id != @question.user.id %>
                <% if current_user.already_liked?(@question) %>
                  <%= link_to question_like_path(@question.id), method: :delete, remote: true do %>
                    <div class = "line_button">❤️<%= @question.likes.count %></div>
                  <% end %>
                <% else %>
                  <%= link_to question_likes_path(@question.id), method: :post, remote: true do %>
                    <div class = "line_button">♡️<%= @question.likes.count %></div>
                  <% end %>
                <% end %>
              <% else %>
                <div class = "line_button">❤️<%= @question.likes.count%></div>
              <% end %>
            <% else%>
              <div class = "line_button">❤️<%= @question.likes.count%></div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    
  <div class="container">
    <div class = "answer-container">
      <% if user_signed_in? && current_user.id != @question.user.id %>
        <%= form_with(model: [@question, @answer], local: true) do |f| %>
          <%= f.text_area name=:text, placeholder: "回答する",class:"textarea" %>
          <%= f.submit "回答", class: "button", size: "40*40" %>
        <% end %>
       <% elsif user_signed_in? && current_user.id == @question.user.id %> 
      <% else%>
        <strong><p><%= link_to '回答するにはログイン/新規登録をしよう', user_session_path, class: 'ac' %></p></strong>
      <% end %>
      <div class= "answers">
        <h4 class= "an4">＜回答一覧＞</h4>
          <% @answers.each do |answer| %>
            <div class= "text"><%= answer.text %>
            </div>
              <div class= "g">
                <%= l answer.created_at %><strong>回答者<%= link_to answer.user.name, "/users/#{answer.user_id}", class:'ac' %></strong>
                <% if user_signed_in?%>
                  <% if current_user.id != @answer.user_id %>
                    <% if current_user.already_liked?(answer) %>
                      <%= link_to answer_nice_path(answer.id), method: :delete, remote: true do %>
                        <div class = "line_button">❤️<%= answer.nices.count %></div>
                      <% end %>
                    <% else %>
                      <%= link_to answer_nices_path(answer.id), method: :post, remote: true do %>
                        <div class = "line_button">♡️<%= answer.nices.count %></div>
                      <% end %>
                    <% end %>
                  <% else %>
                    <div class = "line_button">❤️<%= answer.nices.count%></div>
                  <% end %>
                <% else %>
                  <div class = "line_button">❤️<%= answer.nices.count%></div>
                <% end %>
              </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
      <%= link_to image_tag("fes.png", class:"fes-icon"),"/" %> 
      <ul class='lists-right'>
        <% if user_signed_in? %>
          <li><%= link_to 'Q:質問', new_question_path, class: "post"%>
          <li><%= link_to current_user.name, "/users/#{current_user.id}", class: "post"%> </li>
          <li><%= link_to 'ログアウト',destroy_user_session_path, method: :delete, class: "post"%> </li>
        <% else %>
            <li><%= link_to 'ログイン', user_session_path, class: "post" %></li>
            <li><%= link_to 'ユーザー登録', new_user_registration_path, class: "post" %></li>
        <% end %>
      </ul>
  </div>
</header>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class= "show-box">
  <div class= "box">
    <div class= "q-name">
      <%= @name %>さんの投稿一覧
    </div>
    <% @questions.each do |question| %>
    <div class= "user-text">
      <div class= "rr"><%= question.text %>
        <div class= "date"><%= l question.created_at %>
        </div>
      </div>
    </div>
    <% end %>
    <div class= "answers">
      <h4 class= "an4">＜回答一覧＞</h4>
        <% @answers.each do |answer| %>
          <div class= "text"><%= answer.text %></div>
            <div class= "g">
              <%= l answer.created_at %>
            </div>
          <% end %>
    </div>
  </div>
</div>